### ISSUE TITLE
Cover images don't show

### ISSUE THREAD

**Issue by resdigita** [Undergrid/docker-bicbucstriim#1]
I refer to version 1.5, same issue existed in 1.4.2

In every list of books the cover image is missing, see attached screenshot. The error message complains about a file not found:

> - - - - - - <
Slim Application Error
The application could not run because of the following error:

Details

Type: ErrorException
Code: 2
Message: filesize(): stat failed for /books/Lee Child/A Wanted Man (28)/cover.jpg
File: /config/www/index.php
Line: 1224
Trace

#0 [internal function]: Slim\Slim::handleErrors(2, 'filesize(): sta...', '/config/www/ind...', 1224, Array)
#1 /config/www/index.php(1224): filesize('/books/Lee Chil...')
#2 [internal function]: cover('28')
#3 /config/www/vendor/slim/slim/Slim/Route.php(462): call_user_func_array('cover', Array)
#4 /config/www/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#5 /config/www/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /config/www/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /config/www/lib/BicBucStriim/calibre_config_middleware.php(50): Slim\Middleware\MethodOverride->call()
#8 /config/www/lib/BicBucStriim/login_middleware.php(36): CalibreConfigMiddleware->call()
#9 /config/www/lib/BicBucStriim/own_config_middleware.php(31): LoginMiddleware->call()
#10 /config/www/lib/BicBucStriim/caching_middleware.php(41): OwnConfigMiddleware->call()
#11 /config/www/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): CachingMiddleware->call()
#12 /config/www/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#13 /config/www/index.php(206): Slim\Slim->run()
#14 {main}
> - - - - - - <

If I check the file system in a container terminal, all files do exist (see screenshot). I'm not too familiar with php but it looks to me as if the code handling images don't handle spaces correctly, but the code handling e.g. the download does. The library is a direct copy of the Calibre library without any modification (a Synology cloud station sync). The file and directory names are generated by Calibre as is.

![bbc-missingimages](https://user-images.githubusercontent.com/47404115/52382787-f36c9d80-2a76-11e9-915c-b55f99991947.png)

![containerfilesystem](https://user-images.githubusercontent.com/47404115/52382810-097a5e00-2a77-11e9-81e7-a021342ed7ec.png)

**Comment by Undergrid** [comment]
Hi resdigita,

I can assure you it's not a problem with spaces, my own install has spaces in pretty much every book title and the covers work fine.

I have a few thoughts, but I need more information.  Can you supply a listing of the same directories as you've shown above but in the host operating system and using the -n option for ls, please?  Also can you supply the values specified for the PUID and PGID configuration parameters?

Thanks.
