### ISSUE TITLE
HTTP Error 500 after creating the container

### ISSUE THREAD

**Issue by chjohans** [Undergrid/docker-bicbucstriim#5]
Is this project still alive?

I'm trying to move from a Synology custom package BBS to using docker so I can upgrade the OS on my Synology NAS, the new OS does not support the old BBS package. I've successfully done the same for a few other packages I'm using, all working just fine in DOcker.

But not BitBucStriim, I had an error message for a missing file in "vendor" so I downloaded BBS from their GitHub page and copied to the "vendor" directory to my docker data directory, I placed it under "www". This made the error go away.

B ut I still just get an HTTP 500 error, and "docker logs -f BicBucStriim" does not show any error messages.

Every web request to BBS creates a single entry in the apache access.log:
172.17.0.1 - - [10/May/2022:02:37:33 +0800] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"

I did find an error that referenced to "langs.php" in the apache error.log, I found this file in "lib\BitBucStriim" in the original BBS distro, so I just put the "lib" folder under "www" as well.

But now it complains it cant find "AuthMiddleWare":
[Tue May 10 02:59:33.050567 2022] [php7:error] [pid 294] [client 172.17.0.1:51799] PHP Fatal error:  require_once(): Failed opening required 'AuthMiddleware.php' (include_path='.::./lib/BicBucStriim:./vendor') in /config/www/index.php on line 22

Now it can't be that I'm supposed to put the whole BBS distro into the "www" solder so at this point I'm stuck, any help to offer?

**Comment by Undergrid** [comment]
Please pull the latest version and let me know if it fixes your issue.  Note the instructions in the "Update" section of the README.md if you are upgrading from a previous version.

**Comment by chjohans** [comment]
Thanks a million, the new version works with no issues.!
